hydra:
  searchpath:
    - verl/verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 30768
  max_response_length: 2000
  train_batch_size: 256
  return_raw_chat: True

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      _target_: config.multiturn_config.CustomMultiTurnConfig
      enable: True
      max_assistant_turns: 10
      strict_generation: False
      check_think_tags: False
      use_answer_verification: False